name: Update availability JSON

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # allow manual run

jobs:
  update-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch availability JSON from Apps Script
        run: |
          curl -s "https://script.google.com/macros/s/AKfycbxHYEJxV8KgtBc5u43H4B19912ZvPuvY0ifb_nrQFhQhy31VYiNALJNVhdQQnS9FPEa/exec?mode=full_season" \
            -o data/availability.json


      - name: Commit and push if changed
        run: |
          if git status --porcelain | grep data/availability.json; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add data/availability.json
            git commit -m "Update availability JSON"
            git push
          else
            echo "No changes to commit."
          fi
